// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {platform} from '../models';

export function GetAlerts(arg1:number):Promise<Array<platform.Alert>>;

export function GetDevices():Promise<Array<platform.Device>>;

export function GetStats(arg1:number):Promise<Array<platform.SystemStats>>;
