// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlerts(arg1) {
  return window['go']['main']['App']['GetAlerts'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}
